<div class="btn-group">
<button class="selection btn" onClick="invertAllinSection(this.parentNode);">inverser</button>
<button class="selection btn" onClick="doSimpleinSection(this.parentNode,true);">tout</button>
<button class="selection btn" onClick="doSimpleinSection(this.parentNode,false);">aucun</button>
<button class="selection btn" onClick="doinSection(this.parentNode,'type_fichier','.jpg',true);"><i class="icon-picture"></i> images</button>
<button class="selection btn" onClick="selectUntilSelectedinSection(this.parentNode);"><i class="icon-check"></i> jusque coché</button>
</div>